### ISSUE TITLE
能设置节点折叠嘛？

### ISSUE THREAD

**Issue by shadow1ng** [jan-bar/xmind#4]
比如 st1.Add(name).OnTitle(name)
然后把这个name折叠起来

**Comment by jan-bar** [comment]
@shadow1ng 经过测试将[官方定义](https://github.com/xmindltd/xmind-sdk-js/blob/21e5ccce11448497889d4081f3c1754251ad1ced/src/common/model.ts#L128)这里设置一下 `"branch":"folded"` ，就可以了，我看看能不能补全一下这块功能吧。

**Comment by jan-bar** [comment]
@shadow1ng 我添加了v1.0.8的标签，你用这个版本测试看看有没有问题额。

**Comment by shadow1ng** [comment]
可以的，没啥问题
