### ISSUE TITLE
想请教下，ontitle、oncid的问题

### ISSUE THREAD

**Issue by shadow1ng** [jan-bar/xmind#6]
func (st *Topic) CId(title string) TopicID {
	if title == "" {
		return CentKey
	}
	if st != nil {
		for id, topic := range st.resources {
			// 由于range遍历乱序因此,不保证存在多个title时按照之前添加顺序返回
			if id.IsOrdinary() && topic.Title == title {
				return id // 判断ID长度,剔除特殊ID
			}
		}
	}
	return lastKey // 匹配不到返回最后一次编辑的主题ID
}

是不是改成下面的好点，这样能优先批量子节点里的内容。
aaa.信息
bbb.信息
如何ontitle("bbb").ontitle("信息")，可能会匹配到aaa.信息

func (st *Topic) CId(title string) TopicID {
	if title == "" {
		return CentKey
	}
	if st != nil {
		for _, topic := range st.Children.Attached {
			// 由于range遍历乱序因此,不保证存在多个title时按照之前添加顺序返回
			if topic.ID.IsOrdinary() && topic.Title == title {
				return topic.ID // 判断ID长度,剔除特殊ID
			}
		}
	}
	if st != nil {
		for id, topic := range st.resources {
			// 由于range遍历乱序因此,不保证存在多个title时按照之前添加顺序返回
			if id.IsOrdinary() && topic.Title == title {
				return id // 判断ID长度,剔除特殊ID
			}
		}
	}
	return lastKey // 匹配不到返回最后一次编辑的主题ID
}

**Comment by jan-bar** [comment]
这个我改改吧。。

**Comment by jan-bar** [comment]
@shadow1ng 试试`github.com/jan-bar/xmind v1.0.9-0.20231215063028-c59fbc01ee6a`这个版本，看看没问题我再打tag吧。

**Comment by shadow1ng** [comment]
我这边测试正常

**Comment by jan-bar** [comment]
@shadow1ng 可以切到`v1.0.9`版本额。

**Comment by shadow1ng** [comment]
ok。3q3q，师傅更新得好快

**Comment by jan-bar** [comment]
> ok。3q3q，师傅更新得好快

上班摸鱼不如撸代码舒服啊，哈哈。
